services:

  deadlock-twitch-extension:
    build: .
    ports:
      - "3001:3001"
    networks:
      - deadlock-network

  deadlock-live-events:
    image: ghcr.io/deadlock-api/deadlock-live-events:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - deadlock-network

networks:
  deadlock-network:
    driver: bridge